# Generated by Django 4.2.7 on 2025-09-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='כתובת')),
                ('user_type', models.CharField(choices=[('regular', 'רגיל'), ('admin', 'מנהל'), ('staff', 'צוות'), ('marketer', 'משווק')], default='regular', max_length=20, verbose_name='סוג משתמש')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הצטרפות')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('marketer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.marketer', verbose_name='משווק')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'פרופיל משתמש',
                'verbose_name_plural': 'פרופילי משתמשים',
            },
        ),
    ]
