# Generated by Django 4.2.7 on 2025-09-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='טלפון נוסף'),
        ),
    ]
