# Generated by Django 4.2.7 on 2025-09-07 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הקטגוריה')),
                ('slug', models.SlugField(unique=True, verbose_name='כתובת URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
            ],
            options={
                'verbose_name': 'קטגוריה',
                'verbose_name_plural': 'קטגוריות',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם האירוע')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
            ],
            options={
                'verbose_name': 'אירוע',
                'verbose_name_plural': 'אירועים',
            },
        ),
        migrations.CreateModel(
            name='Kashrut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='רמת כשרות')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
            ],
            options={
                'verbose_name': 'כשרות',
                'verbose_name_plural': 'כשרויות',
            },
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=50, verbose_name='שם משפחה')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='משתמש במערכת')),
            ],
            options={
                'verbose_name': 'משווק',
                'verbose_name_plural': 'משווקים',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='מספר הזמנה')),
                ('first_name', models.CharField(max_length=50, verbose_name='שם פרטי')),
                ('last_name', models.CharField(max_length=50, verbose_name='שם משפחה')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='כתובת')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='עיר')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='מיקוד')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום כולל')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='כמות פריטים')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('processing', 'בטיפול'), ('shipped', 'נשלח'), ('delivered', 'הגיע'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס הזמנה')),
                ('payment_status', models.CharField(choices=[('pending', 'ממתין לתשלום'), ('paid', 'שולם'), ('failed', 'נכשל'), ('refunded', 'הוחזר')], default='pending', max_length=20, verbose_name='מצב תשלום')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הזמנה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.event', verbose_name='אירוע')),
                ('marketer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.marketer', verbose_name='משווק')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם המוצר')),
                ('slug', models.SlugField(unique=True, verbose_name='כתובת URL')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('supplier', models.CharField(max_length=200, verbose_name='ספק')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
                ('stock', models.PositiveIntegerField(default=999999, help_text='ברירת מחדל: אינסופי', verbose_name='מלאי')),
                ('unlimited_stock', models.BooleanField(default=True, verbose_name='מלאי אינסופי')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='כמות הזמנות')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='תמונה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='קטגוריה')),
                ('kashrut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kashrut', verbose_name='כשרות')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר ברגע ההזמנה')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='הזמנה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'פריט בהזמנה',
                'verbose_name_plural': 'פריטים בהזמנה',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='מוצר')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'פריט בעגלה',
                'verbose_name_plural': 'פריטים בעגלה',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
