# Generated by Django 4.2.7 on 2025-09-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='שם משפחה'),
        ),
    ]
